name: Propose a change impacting the content of the INSPIRE registry
description: Content change proposal
title: "[Change]"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please replace these lines with a brief summary of your change proposal. Please remember that this issue template is reserved only to the appointed Submitting Organisations.

        Remember to specify all the required information in order to facilitate the correct evaluation and eventual implementation of the proposed changes. Detailed guidelines and examples proposals are available here.

  - type: input
    id: URI
    attributes:
      label: URI
      description: The URI of the register/reference code.
    validations:
      required: true

  - type: input
    id: motiv
    attributes:
      label: Motivation
      description: The rationale or motivation behind this proposal.
    validations:
      required: true

  - type: textarea
    id: proposedChange
    attributes:
      label: Proposed change
    validations:
      required: true      

  - type: input
    id: changeType
    attributes:
      label: Change type.
      description: Addition, clarification, supersession, invalidation, retirement.
    validations:
      required: true    

  - type: markdown
    attributes:
      value: |
        To help us understand the proposal, you may want to include:

  - type: input
    id: link 
    attributes:
      label: Link with further information on the proposal
    validations:
      required: false   

  - type: textarea
    id: material 
    attributes:
      label: Diagrams, mockups or screenshots that illustrate the proposal
    validations:
      required: false   


        


