name: Report an issue, or ask a question on the user interface, API… of the INSPIRE register federation
description: Report an issue or ask a question not impacting the content of the INSPIRE register federation (e.g. provide feedback related to the INSPIRE register federation user interface).
title: "[Report]"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please replace these lines with a brief summary of your change proposal. Please remember that this issue template is reserved only to the appointed Submitting Organisations.

        Remember to specify all the required information in order to facilitate the correct evaluation and eventual implementation of the proposed changes. Detailed guidelines and examples proposals are available here.
